README.md

Before we described two different ways of running SourceCred (with yarn and running sourcecred directly). For
the purposes of the example instance, users should pretty much only be using the yarn commands. Also moved the instructions up
a bit so they dont get lost in the huge wall of text for plugin config.

Simplify and consolidate usage instructions

---

README.md

Currently, we give the following URL template for giving a bot permissions:
```
https://discordapp.com/api/oauth2/authorize?client_id=${CLIENT_ID}&scope=bot&permissions=66560`
```
This was throwing the following error:
`{client_id": ["Value \"$742897388204720201\" is not snowflake."]}`
Found an [article](https://www.digitaltrends.com/gaming/how-to-make-a-discord-bot/) on setting up a bot that passes the value '8' instead of '66560' as the permissions value. This worked locally. This PR changes the value to '8' in both places it appears. 
@hammadj confirmed in [chat](https://discordapp.com/channels/453243919774253079/454007907663740939/745046374676168804) that we should make this change 'if 8 works', but someone other than me should probably verify that 8 works.

Fix bug Discord setup instructions

---

.github/workflows/distribute-grain.yml
README.md

Copied over the grain distribution action from SourceCred's cred instance and added a guide in the README explaining
how grain distributions work and how to configure them.
Test Plan:
- Ensure the distribute-grain action successfully runs and creates a PR with updated ledger.
- Sanity check README guide on grain distributions

Setup Grain Distribution action and add README guide

---

README.md
config/currencyDetails.json

Documents the process in which users can customize the name of their Grain.
Test Plan: Ensure that updating the name in currencyDetails actually reflects in the UI

Add default currencyDetails.json + customization instructions

---

README.md

Removed Discord configuration instructions, as we have updated config instructions in the main docs now. Added text pointing to new instructions. 
@hammadj, feel free to change the new text if you want.

Moving Discord config instructions to main docs

---

config/dependencies.json
package.json
yarn.lock

This commit adds SourceCred as a default dependency with a weight of
0.05.
Test plan: Regenerate the instance and load the frontend; you'll see
that there's a SourceCred identity with about 5% of the total Cred.
Note: Running the test plan will modify the `config/dependencies.json`,
because it will choose an id for SourceCred. We need to think about how
to ensure the users get a clean state for their own instance, c.f.
discussion in #8.

Add SourceCred as a default dependency

---

config/dependencies.json
package.json
yarn.lock

This also modifies the dependencies.json, so that now we define a start
period, and the Cred minting only kicks in after that period. I set the
initial period to be the next logical Cred period (i.e. starting next
Sunday), so if someone adopts SourceCred today, it will only start
minting dependency Cred for SC in the first week where SC was already
running. We should set up a GitHub action to keep moving the start date
to next Sunday.
Test plan: `yarn load; yarn graph; yarn score; yarn site; yarn serve`
and verify that there are no errors.

Upgrade to SourceCred 16

---

package.json
yarn.lock

This bumps the sourcecred version to 0.7.1
after changing package.lock, I ran yarn
will be tested after merge by CI

Upgrade to sourcecred 0.7.1

---

README.md
sourcecred.json

Disabled plugins so users dont have to deal with errors like "missing DISCORD_TOKEN" and instead can choose
to opt in to only the plugins they want to use.
Test Plan: Ensure no plugins are loaded / run when calling SourceCred commands

Disable all plugins by default

---

config/dependencies.json

Updates the dependencies.json file to match the new API, the current config causes errors when setting up an instance.
With https://github.com/sourcecred/sourcecred/pull/2291, running SourceCred will now set the period to start from 1 week of the user setting up their cred instance.

Fix default dependencies.json config file

---

README.md
package.json

Reduced the 5 commands needed to run a SC instance down to 2 commands. Based on my experience running an instance and helping others run an instance, the only two things they really want to do are "load the data" and "run SourceCred". Having separate `site` and `serve` command is just leaking implementation details to the user, and the graph/score/site commands run fast enough to group them together into the `yarn start` command. This also limits the chance that the user updates the weights but forgets to run graph/score before running site/serve and gets frustrated or confused as to why their Cred scores aren't updating.
I also relocated the distributing grain instructions to be co-located with the grain command instructions instead of being at the bottom of the README.
Test Plan: Follow …

Simplify process for running SourceCred and improve README

---

README.md
package.json

Instructions weren't clean on when and why users should run the `yarn load` command again. This gives more context to the commands and explains more explicitly what yarn start doesn't do.
Also removed redundant command in `yarn start`

Cleanup command and improve instructions for reloading data

---

package.json
yarn.lock

With Dependabot (#28), users will be notified of the latest sourcecred
releases, so it behooves us to unpin this dependency
test plan: N/A

Bump and unpin SourceCred dependency

---

.github/workflows/generate-instance.yml

fixes #25
The package.json no longer has the commands that are being used in the Github Action workflow.
This PR updates the workflow file to use the sourcecred go command instead
Test Plan: Ran the command locally and it succeeded, will update the MetaGame instance with this to ensure it works in prod

Update github action for new CLI commands

---

.github/workflows/generate-instance.yml

The error was a result of GitHub [deprecating the set-env API for actions in October 2020](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/). It was fixed by updating the `github-pages-deploy-action` to the latest version which stopped using the deprecated API.
Test Plan: Ran the updated version of the GitHub action on MetaGame's cred instance, no longer had the error: https://github.com/MetaFam/XP/runs/1410470604

Fix "set-env command is disabled" error

---

.github/workflows/distribute-grain.yml

test plan: diff with the distribute-grain.yml file in the
sourcecred/cred repo should be identical, except for line 60, the
reviewers param in the sourcecred/cred repo

Update distribute-grain action to utilize updated CLI

---

README.md

Added instructions for Recent (`recentWeeklyDecayRate`) policy. paired-with @KuraFire (reused their example and wording from Discord help message). 
Added example `grain.json` file. 
Capitalized several instances of cred->Cred.

Add instructions for Recent policy, minor formatting

---

.github/workflows/generate-instance.yml

This allows serving the gh-pages branch, in order to easily test against prod data. See https://github.com/sourcecred/cred/pull/247 for details and test plan.

Add package.json to gh-pages deployment

---

package.json

The start command was re-loading, data, even though it's not supposed to. This made it impossible to re-generate the graph without re-loading data (too time-consuming for most workflows). 
This PR implements a change suggested by @blueridger in #tech-support ([link](https://discord.com/channels/453243919774253079/718263631158050896/827683756793790486)), which worked for me locally. 
1. On an existing instance, run `yarn load` (if data not already loaded)
2. Run `yarn start`
The start command should recalculate graph, scores, and run a local instance, without re-loading data. 
P.S. My fix worked locally on OSX Mojave 10.14.6

Update start command to not re-load data

---

.github/workflows/distribute-grain.yml
.github/workflows/generate-instance.yml
README.md

Since the load step was using the default actions token, it did not have access to private repos, which broke the `load` step when an instance tried to include private repos using our github plugin.
https://github.com/blueridger/ballena-cred/runs/2611875978?check_suite_focus=true#step:4:217

Use user-provided github token to support private repos

---

.github/workflows/generate-instance.yml

The footprint is small, and it is used by metagov's instance heavily, and I think it might be a simple api to read data from the SC instance through other modules

add analysis command in the github action

---

.github/workflows/distribute-grain.yml

If our users want to commit to main, we should make sure they are doing it right.

Add commit-to-main option to DistributeGrain
